package dev.brandonvargas.veganscanner.feature.scanner.domain.rules

import dev.brandonvargas.veganscanner.core.model.IngredientVeganStatus
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * A trimmed copy of the Open Food Facts ingredient taxonomy (ODbL): about 5,000 ingredients with their
 * effective vegan status and English/Spanish names. Generated by `./gradlew :shared:feature:scanner:updateOffTaxonomy`.
 */
@Serializable
internal data class OffTaxonomy(val entries: List<Entry>) {
    @Serializable
    data class Entry(
        val id: String,
        val status: Status,
        /** True when the status comes from a curated override in `ingredients.json` (e.g. sugar). */
        val overridden: Boolean = false,
        val en: List<String> = emptyList(),
        val es: List<String> = emptyList(),
        /** Additive code such as `E120`. */
        val e: String? = null,
    )

    @Serializable
    enum class Status(val ingredientStatus: IngredientVeganStatus) {
        @SerialName("yes")
        YES(IngredientVeganStatus.YES),

        @SerialName("no")
        NO(IngredientVeganStatus.NO),

        @SerialName("maybe")
        MAYBE(IngredientVeganStatus.MAYBE),
    }

    companion object {
        private val json = Json { ignoreUnknownKeys = true }

        fun parse(source: String): OffTaxonomy = json.decodeFromString(serializer(), source)

        val Empty = OffTaxonomy(emptyList())

        /** The taxonomy bundled with the app. */
        val Bundled: OffTaxonomy by lazy { parse(OFF_TAXONOMY_JSON) }
    }
}

/**
 * Spanish names for taxonomy ingredients that Open Food Facts only names in English: Wikidata labels and Gemini
 * translations. Generated by `./gradlew :shared:feature:scanner:translateOffTaxonomy`.
 */
@Serializable
internal data class OffTaxonomyTranslations(val entries: Map<String, Translation>) {
    @Serializable
    data class Translation(val es: List<String> = emptyList())

    fun spanish(id: String): List<String> = entries[id]?.es.orEmpty()

    companion object {
        private val json = Json { ignoreUnknownKeys = true }

        fun parse(source: String): OffTaxonomyTranslations = json.decodeFromString(serializer(), source)

        val Empty = OffTaxonomyTranslations(emptyMap())

        /** The translations bundled with the app. */
        val Bundled: OffTaxonomyTranslations by lazy { parse(OFF_TAXONOMY_ES_JSON) }
    }
}
